-- Auth service schema (auth_db). Matches JPA entities under ddl-auto=validate.

CREATE TABLE ROLES (
    ID   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE USERS (
    ID         UUID PRIMARY KEY,
    USERNAME   VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD   VARCHAR(255) NOT NULL,
    EMAIL      VARCHAR(200) NOT NULL UNIQUE,
    STATUS     VARCHAR(20)  DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT now(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE USER_ROLES (
    USER_ID UUID NOT NULL,
    ROLE_ID UUID NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE
);

CREATE TABLE REFRESH_TOKENS (
    ID          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USER_ID     UUID NOT NULL,
    TOKEN       VARCHAR(500) NOT NULL UNIQUE,
    EXPIRY_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE TABLE PASSWORD_RESET_TOKENS (
    ID          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USER_ID     UUID NOT NULL,
    TOKEN       VARCHAR(200) NOT NULL UNIQUE,
    EXPIRY_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    USED        BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE INDEX idx_prt_token ON PASSWORD_RESET_TOKENS (TOKEN);

CREATE TABLE AUDIT_LOGS (
    ID          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USERNAME    VARCHAR(100) NOT NULL,
    ACTION      VARCHAR(100) NOT NULL,
    DETAIL      TEXT,
    IP_ADDRESS  VARCHAR(50),
    SUCCESS     BOOLEAN NOT NULL,
    OCCURRED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_audit_username ON AUDIT_LOGS (USERNAME);
CREATE INDEX idx_audit_occurred_at ON AUDIT_LOGS (OCCURRED_AT DESC);
