-- V3__update_auth_schema_uuid.sql
DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

CREATE TABLE ROLES (
    ID   UUID         PRIMARY KEY,
    NAME VARCHAR(50)  UNIQUE NOT NULL
);

CREATE TABLE USERS (
    ID         UUID         PRIMARY KEY,
    USERNAME   VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD   VARCHAR(255) NOT NULL,
    EMAIL      VARCHAR(200) UNIQUE NOT NULL,
    STATUS     VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE USER_ROLES (
    USER_ID UUID NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    ROLE_ID UUID NOT NULL REFERENCES ROLES(ID) ON DELETE CASCADE,
    PRIMARY KEY (USER_ID, ROLE_ID)
);

CREATE TABLE REFRESH_TOKENS (
    ID          UUID         PRIMARY KEY,
    USER_ID     UUID         NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    TOKEN       VARCHAR(500) UNIQUE NOT NULL,
    EXPIRY_DATE TIMESTAMPTZ  NOT NULL
);
