-- V5__add_password_reset_audit_log.sql

CREATE TABLE PASSWORD_RESET_TOKENS (
    ID          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    USER_ID     UUID         NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    TOKEN       VARCHAR(200) UNIQUE NOT NULL,
    EXPIRY_DATE TIMESTAMPTZ  NOT NULL,
    USED        BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_prt_token ON PASSWORD_RESET_TOKENS(TOKEN);

CREATE TABLE AUDIT_LOGS (
    ID          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    USERNAME    VARCHAR(100) NOT NULL,
    ACTION      VARCHAR(100) NOT NULL,
    DETAIL      TEXT,
    IP_ADDRESS  VARCHAR(50),
    SUCCESS     BOOLEAN      NOT NULL DEFAULT TRUE,
    OCCURRED_AT TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_audit_username    ON AUDIT_LOGS(USERNAME);
CREATE INDEX idx_audit_occurred_at ON AUDIT_LOGS(OCCURRED_AT DESC);
