-- Reporting service schema (reporting_db). Kafka-projected; no seed.

CREATE TABLE STUDENT_REPORT (
    ID                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    STUDENT_ID        UUID NOT NULL UNIQUE,
    FIRST_NAME        VARCHAR(200) NOT NULL,
    LAST_NAME         VARCHAR(200),
    TOTAL_ENROLLMENTS INTEGER NOT NULL,
    ACTIVE_FEE_BALANCE NUMERIC(12, 2) NOT NULL,
    LAST_PAYMENT_DATE TIMESTAMP
);

CREATE TABLE TEACHER_REPORT (
    ID                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    TEACHER_ID            UUID NOT NULL UNIQUE,
    EMPLOYEE_CODE         VARCHAR(50),
    FIRST_NAME            VARCHAR(200) NOT NULL,
    LAST_NAME             VARCHAR(200),
    TOTAL_CLASSES         INTEGER NOT NULL,
    ATTENDANCE_PERCENTAGE NUMERIC(5, 2) NOT NULL
);

CREATE TABLE REVENUE_SUMMARY (
    ID              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    BILLING_MONTH   INTEGER NOT NULL,
    BILLING_YEAR    INTEGER NOT NULL,
    TOTAL_BILLED    NUMERIC(12, 2) NOT NULL,
    TOTAL_COLLECTED NUMERIC(12, 2) NOT NULL,
    OUTSTANDING     NUMERIC(12, 2) NOT NULL,
    STUDENT_COUNT   INTEGER NOT NULL,
    CONSTRAINT uq_revenue_summary UNIQUE (BILLING_MONTH, BILLING_YEAR)
);

CREATE TABLE ATTENDANCE_SUMMARY (
    ID               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    SUBJECT_TYPE     VARCHAR(20) NOT NULL,
    SUBJECT_ID       UUID NOT NULL,
    SUBJECT_NAME     VARCHAR(200) NOT NULL,
    COURSE_ID        UUID,
    COURSE_NAME      VARCHAR(200),
    ATTENDANCE_MONTH INTEGER NOT NULL,
    ATTENDANCE_YEAR  INTEGER NOT NULL,
    TOTAL_DAYS       INTEGER NOT NULL,
    PRESENT_DAYS     INTEGER NOT NULL,
    ABSENT_DAYS      INTEGER NOT NULL,
    LEAVE_DAYS       INTEGER NOT NULL,
    CONSTRAINT uq_attendance_summary UNIQUE (SUBJECT_TYPE, SUBJECT_ID, ATTENDANCE_MONTH, ATTENDANCE_YEAR)
);
