-- V2__update_reporting_schema_uuid.sql
DROP TABLE IF EXISTS attendance_summary CASCADE;
DROP TABLE IF EXISTS revenue_summary CASCADE;
DROP TABLE IF EXISTS student_report CASCADE;
DROP TABLE IF EXISTS teacher_report CASCADE;

CREATE TABLE ATTENDANCE_SUMMARY (
    ID               UUID        PRIMARY KEY,
    SUBJECT_TYPE     VARCHAR(20) NOT NULL,
    SUBJECT_ID       UUID        NOT NULL,
    SUBJECT_NAME     VARCHAR(200) NOT NULL,
    ATTENDANCE_MONTH INT         NOT NULL,
    ATTENDANCE_YEAR  INT         NOT NULL,
    TOTAL_DAYS       INT         NOT NULL DEFAULT 0,
    PRESENT_DAYS     INT         NOT NULL DEFAULT 0,
    ABSENT_DAYS      INT         NOT NULL DEFAULT 0,
    LEAVE_DAYS       INT         NOT NULL DEFAULT 0,
    CONSTRAINT uq_attendance_summary UNIQUE (SUBJECT_TYPE, SUBJECT_ID, ATTENDANCE_MONTH, ATTENDANCE_YEAR)
);

CREATE TABLE REVENUE_SUMMARY (
    ID              UUID           PRIMARY KEY,
    BILLING_MONTH   INT            NOT NULL,
    BILLING_YEAR    INT            NOT NULL,
    TOTAL_BILLED    NUMERIC(12,2)  NOT NULL DEFAULT 0,
    TOTAL_COLLECTED NUMERIC(12,2)  NOT NULL DEFAULT 0,
    OUTSTANDING     NUMERIC(12,2)  NOT NULL DEFAULT 0,
    STUDENT_COUNT   INT            NOT NULL DEFAULT 0,
    CONSTRAINT uq_revenue_summary UNIQUE (BILLING_MONTH, BILLING_YEAR)
);

CREATE TABLE STUDENT_REPORT (
    ID                 UUID           PRIMARY KEY,
    STUDENT_ID         UUID           NOT NULL UNIQUE,
    FIRST_NAME         VARCHAR(200)   NOT NULL,
    LAST_NAME          VARCHAR(200),
    TOTAL_ENROLLMENTS  INT            NOT NULL DEFAULT 0,
    ACTIVE_FEE_BALANCE NUMERIC(12,2)  NOT NULL DEFAULT 0,
    LAST_PAYMENT_DATE  TIMESTAMP
);

CREATE TABLE TEACHER_REPORT (
    ID                    UUID          PRIMARY KEY,
    TEACHER_ID            UUID          NOT NULL UNIQUE,
    EMPLOYEE_CODE         VARCHAR(50),
    FIRST_NAME            VARCHAR(200)  NOT NULL,
    LAST_NAME             VARCHAR(200),
    TOTAL_CLASSES         INT           NOT NULL DEFAULT 0,
    ATTENDANCE_PERCENTAGE NUMERIC(5,2)  NOT NULL DEFAULT 0
);
