-- V3__notifications_read_and_announcements.sql
-- Adds read tracking + title/type to notifications, and announcement / teacher-permission tables.

ALTER TABLE NOTIFICATIONS ADD COLUMN IS_READ  BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE NOTIFICATIONS ADD COLUMN READ_AT  TIMESTAMP;
ALTER TABLE NOTIFICATIONS ADD COLUMN TITLE    VARCHAR(500);
ALTER TABLE NOTIFICATIONS ADD COLUMN TYPE     VARCHAR(50);

CREATE INDEX idx_notifications_user_id_is_read ON NOTIFICATIONS(USER_ID, IS_READ);

-- Announcements are inbox-only (no email/SMS); allow a 'NONE' channel.
ALTER TABLE NOTIFICATIONS DROP CONSTRAINT IF EXISTS chk_notifications_channel;
ALTER TABLE NOTIFICATIONS ADD CONSTRAINT chk_notifications_channel
    CHECK (CHANNEL IN ('EMAIL', 'SMS', 'BOTH', 'NONE'));

CREATE TABLE ANNOUNCEMENTS (
    ID               UUID          PRIMARY KEY,
    TITLE            VARCHAR(500)  NOT NULL,
    BODY             TEXT          NOT NULL,
    AUDIENCE         VARCHAR(30)   NOT NULL,
    SENDER_USER_ID   UUID,
    SENDER_ROLE      VARCHAR(30),
    RECIPIENT_COUNT  INTEGER       NOT NULL DEFAULT 0,
    CREATED_AT       TIMESTAMP     NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_announcements_audience
        CHECK (AUDIENCE IN ('ALL_STUDENTS', 'ALL_TEACHERS', 'TEACHER_STUDENTS'))
);

CREATE INDEX idx_announcements_created_at ON ANNOUNCEMENTS(CREATED_AT DESC);

CREATE TABLE TEACHER_BROADCAST_PERMISSIONS (
    TEACHER_ID     UUID          PRIMARY KEY,
    CAN_BROADCAST  BOOLEAN       NOT NULL DEFAULT FALSE,
    UPDATED_AT     TIMESTAMP     NOT NULL DEFAULT NOW()
);
