-- Attendance service schema (attendance_db).

CREATE TABLE CLASS_SESSION (
    ID           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CLASS_ID     UUID NOT NULL,
    COURSE_ID    UUID,
    SESSION_DATE DATE NOT NULL,
    START_TIME   TIME,
    END_TIME     TIME,
    STATUS       VARCHAR(20) NOT NULL,
    CONSTRAINT uq_class_session_class_date UNIQUE (CLASS_ID, SESSION_DATE)
);

CREATE INDEX idx_class_session_class_id ON CLASS_SESSION (CLASS_ID);

CREATE TABLE STUDENT_ATTENDANCE (
    ID              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    STUDENT_ID      UUID NOT NULL,
    CLASS_ID        UUID NOT NULL,
    COURSE_ID       UUID,
    SESSION_ID      UUID,
    ATTENDANCE_DATE DATE NOT NULL,
    STATUS          VARCHAR(20) NOT NULL,
    REMARKS         TEXT,
    CONSTRAINT uq_student_attendance UNIQUE (STUDENT_ID, CLASS_ID, ATTENDANCE_DATE),
    CONSTRAINT fk_student_attendance_session FOREIGN KEY (SESSION_ID) REFERENCES CLASS_SESSION (ID)
);

CREATE INDEX idx_student_attendance_student_date ON STUDENT_ATTENDANCE (STUDENT_ID, ATTENDANCE_DATE);
CREATE INDEX idx_student_attendance_class_date ON STUDENT_ATTENDANCE (CLASS_ID, ATTENDANCE_DATE);

CREATE TABLE TEACHER_ATTENDANCE (
    ID              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    TEACHER_ID      UUID NOT NULL,
    ATTENDANCE_DATE DATE NOT NULL,
    STATUS          VARCHAR(20) NOT NULL,
    REMARKS         TEXT,
    CONSTRAINT uq_teacher_attendance UNIQUE (TEACHER_ID, ATTENDANCE_DATE)
);

CREATE INDEX idx_teacher_attendance_date ON TEACHER_ATTENDANCE (ATTENDANCE_DATE);

CREATE TABLE ATTENDANCE_CORRECTION (
    ID                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    STUDENT_ATTENDANCE_ID  UUID NOT NULL,
    STUDENT_ID             UUID NOT NULL,
    CLASS_ID               UUID NOT NULL,
    ATTENDANCE_DATE        DATE NOT NULL,
    REQUESTED_STATUS       VARCHAR(20) NOT NULL,
    REASON                 TEXT,
    REQUESTED_BY_TEACHER_ID UUID NOT NULL,
    STATUS                 VARCHAR(20) NOT NULL,
    REVIEWED_BY_PRINCIPAL_ID UUID,
    REVIEW_NOTE            TEXT,
    CREATED_AT             TIMESTAMP WITH TIME ZONE NOT NULL,
    REVIEWED_AT            TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_correction_status ON ATTENDANCE_CORRECTION (STATUS);
CREATE INDEX idx_correction_teacher ON ATTENDANCE_CORRECTION (REQUESTED_BY_TEACHER_ID);
