-- V3__class_session.sql
CREATE TABLE CLASS_SESSION (
    ID           UUID         PRIMARY KEY,
    CLASS_ID     UUID         NOT NULL,
    COURSE_ID    UUID,
    SESSION_DATE DATE         NOT NULL,
    START_TIME   TIME,
    END_TIME     TIME,
    STATUS       VARCHAR(20)  NOT NULL DEFAULT 'SCHEDULED',
    CONSTRAINT uq_class_session_class_date UNIQUE (CLASS_ID, SESSION_DATE)
);

CREATE INDEX idx_class_session_class_date ON CLASS_SESSION (CLASS_ID, SESSION_DATE);

-- Additive reference from attendance rows to the session they belong to.
-- Existing (STUDENT_ID, CLASS_ID, ATTENDANCE_DATE) unique constraint is retained.
ALTER TABLE STUDENT_ATTENDANCE ADD COLUMN SESSION_ID UUID;
ALTER TABLE STUDENT_ATTENDANCE ADD COLUMN COURSE_ID UUID;

ALTER TABLE STUDENT_ATTENDANCE
    ADD CONSTRAINT fk_student_attendance_session
    FOREIGN KEY (SESSION_ID) REFERENCES CLASS_SESSION (ID);
