-- Step 6 (R10, R11): re-key STUDENT_ATTENDANCE to (student_id, timetable_id, attendance_date)
-- with course_id as a scope column. Retire the CLASS_SESSION / COVER_UP_CLASS machinery
-- (decision 8.1) in favour of the add-student make-up flow. Dev DBs are reseeded, so this is a
-- destructive re-key with no data preservation.

ALTER TABLE STUDENT_ATTENDANCE DROP CONSTRAINT IF EXISTS fk_student_attendance_session;
ALTER TABLE STUDENT_ATTENDANCE DROP CONSTRAINT IF EXISTS uq_student_attendance;
DROP INDEX IF EXISTS idx_student_attendance_class_date;

ALTER TABLE STUDENT_ATTENDANCE DROP COLUMN IF EXISTS SESSION_ID;
ALTER TABLE STUDENT_ATTENDANCE DROP COLUMN IF EXISTS CLASS_ID;

ALTER TABLE STUDENT_ATTENDANCE ADD COLUMN TIMETABLE_ID UUID;
UPDATE STUDENT_ATTENDANCE SET TIMETABLE_ID = gen_random_uuid() WHERE TIMETABLE_ID IS NULL;
ALTER TABLE STUDENT_ATTENDANCE ALTER COLUMN TIMETABLE_ID SET NOT NULL;
ALTER TABLE STUDENT_ATTENDANCE ALTER COLUMN COURSE_ID SET NOT NULL;

ALTER TABLE STUDENT_ATTENDANCE
    ADD CONSTRAINT uq_student_attendance UNIQUE (STUDENT_ID, TIMETABLE_ID, ATTENDANCE_DATE);

CREATE INDEX idx_student_attendance_timetable_date
    ON STUDENT_ATTENDANCE (TIMETABLE_ID, ATTENDANCE_DATE);

DROP TABLE IF EXISTS CLASS_SESSION;

-- Step 7 (R12): re-key TEACHER_ATTENDANCE to (teacher_id, timetable_id, attendance_date) + course_id.
ALTER TABLE TEACHER_ATTENDANCE DROP CONSTRAINT IF EXISTS uq_teacher_attendance;
DROP INDEX IF EXISTS idx_teacher_attendance_class_date;

ALTER TABLE TEACHER_ATTENDANCE DROP COLUMN IF EXISTS CLASS_ID;

ALTER TABLE TEACHER_ATTENDANCE ADD COLUMN TIMETABLE_ID UUID;
UPDATE TEACHER_ATTENDANCE SET TIMETABLE_ID = gen_random_uuid() WHERE TIMETABLE_ID IS NULL;
ALTER TABLE TEACHER_ATTENDANCE ALTER COLUMN TIMETABLE_ID SET NOT NULL;
ALTER TABLE TEACHER_ATTENDANCE ALTER COLUMN COURSE_ID SET NOT NULL;

ALTER TABLE TEACHER_ATTENDANCE
    ADD CONSTRAINT uq_teacher_attendance UNIQUE (TEACHER_ID, TIMETABLE_ID, ATTENDANCE_DATE);

CREATE INDEX idx_teacher_attendance_timetable_date
    ON TEACHER_ATTENDANCE (TIMETABLE_ID, ATTENDANCE_DATE);
