FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY common-library/ common-library/
ARG SERVICE_NAME
COPY ${SERVICE_NAME}/ ${SERVICE_NAME}/
RUN mvn -pl ${SERVICE_NAME} -am clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
ARG SERVICE_NAME
ARG SERVICE_PORT=8080
ENV SERVER_PORT=${SERVICE_PORT}
COPY --from=build /app/${SERVICE_NAME}/target/*.jar app.jar
EXPOSE ${SERVICE_PORT}
ENTRYPOINT ["java", "-jar", "app.jar"]
