-- Payment service schema (payment_db).

CREATE TABLE ENROLLMENT_CACHE (
    ENROLLMENT_ID UUID PRIMARY KEY,
    STUDENT_ID    UUID NOT NULL,
    COURSE_ID     UUID NOT NULL,
    COURSE_FEE    NUMERIC(12, 2) NOT NULL,
    STATUS        VARCHAR(20) NOT NULL
);

CREATE INDEX idx_enrollment_cache_student_id ON ENROLLMENT_CACHE (STUDENT_ID);
CREATE INDEX idx_enrollment_cache_status ON ENROLLMENT_CACHE (STATUS);

CREATE TABLE STUDENT_FEE_CYCLES (
    ID                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    STUDENT_ID         UUID NOT NULL,
    BILLING_MONTH      INTEGER NOT NULL,
    BILLING_YEAR       INTEGER NOT NULL,
    TOTAL_AMOUNT       NUMERIC(12, 2) NOT NULL,
    PAID_AMOUNT        NUMERIC(12, 2) NOT NULL,
    OUTSTANDING_AMOUNT NUMERIC(12, 2) NOT NULL,
    STATUS             VARCHAR(20) NOT NULL,
    GENERATED_DATE     TIMESTAMP,
    DUE_DATE           TIMESTAMP,
    CONSTRAINT uq_student_fee_cycles_student_month_year UNIQUE (STUDENT_ID, BILLING_MONTH, BILLING_YEAR)
);

CREATE INDEX idx_fee_cycles_student_id ON STUDENT_FEE_CYCLES (STUDENT_ID);
CREATE INDEX idx_fee_cycles_status ON STUDENT_FEE_CYCLES (STATUS);
CREATE INDEX idx_fee_cycles_student_status ON STUDENT_FEE_CYCLES (STUDENT_ID, STATUS);

CREATE TABLE STUDENT_FEE_DETAILS (
    ID                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    FEE_CYCLE_ID          UUID NOT NULL,
    STUDENT_ID            UUID NOT NULL,
    ENROLLMENT_ID         UUID NOT NULL,
    COURSE_ID             UUID NOT NULL,
    COURSE_FEE            NUMERIC(12, 2) NOT NULL,
    ALLOCATED_PAID_AMOUNT NUMERIC(12, 2) NOT NULL,
    OUTSTANDING_AMOUNT    NUMERIC(12, 2) NOT NULL,
    STATUS                VARCHAR(20) NOT NULL,
    CONSTRAINT uq_student_fee_details_cycle_enrollment UNIQUE (FEE_CYCLE_ID, ENROLLMENT_ID),
    CONSTRAINT fk_fee_details_cycle FOREIGN KEY (FEE_CYCLE_ID) REFERENCES STUDENT_FEE_CYCLES (ID) ON DELETE CASCADE
);

CREATE INDEX idx_fee_details_cycle_id ON STUDENT_FEE_DETAILS (FEE_CYCLE_ID);
CREATE INDEX idx_fee_details_student_id ON STUDENT_FEE_DETAILS (STUDENT_ID);

CREATE TABLE PAYMENTS (
    ID                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    FEE_CYCLE_ID          UUID NOT NULL,
    STUDENT_ID            UUID NOT NULL,
    AMOUNT                NUMERIC(12, 2) NOT NULL,
    PAYMENT_MODE          VARCHAR(50) NOT NULL,
    TRANSACTION_REFERENCE VARCHAR(200),
    PAYMENT_DATE          TIMESTAMP,
    REMARKS               TEXT,
    CONSTRAINT fk_payments_cycle FOREIGN KEY (FEE_CYCLE_ID) REFERENCES STUDENT_FEE_CYCLES (ID)
);

CREATE INDEX idx_payments_cycle_id ON PAYMENTS (FEE_CYCLE_ID);
CREATE INDEX idx_payments_student_id ON PAYMENTS (STUDENT_ID);

CREATE TABLE PAYMENT_ALLOCATIONS (
    ID               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    PAYMENT_ID       UUID NOT NULL,
    FEE_DETAIL_ID    UUID NOT NULL,
    ALLOCATED_AMOUNT NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_allocations_payment FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENTS (ID) ON DELETE CASCADE,
    CONSTRAINT fk_allocations_fee_detail FOREIGN KEY (FEE_DETAIL_ID) REFERENCES STUDENT_FEE_DETAILS (ID)
);

CREATE INDEX idx_allocations_payment_id ON PAYMENT_ALLOCATIONS (PAYMENT_ID);
CREATE INDEX idx_allocations_fee_detail_id ON PAYMENT_ALLOCATIONS (FEE_DETAIL_ID);
