-- Revenue-share support (institute/teacher share) on the payment dashboard.

-- EnrollmentCache: teacher attribution + frozen share rule for the recurring/monthly line.
ALTER TABLE ENROLLMENT_CACHE ADD COLUMN TEACHER_ID UUID NULL;
ALTER TABLE ENROLLMENT_CACHE ADD COLUMN INSTITUTE_SHARE_TYPE VARCHAR(10) NULL;
ALTER TABLE ENROLLMENT_CACHE ADD COLUMN INSTITUTE_SHARE_VALUE NUMERIC(12,2) NULL DEFAULT 0;

-- StudentFeeDetail: teacher attribution, frozen share rule, resolved amounts (null until PAID),
-- and the auditable principal override.
ALTER TABLE STUDENT_FEE_DETAILS ADD COLUMN TEACHER_ID UUID NULL;
ALTER TABLE STUDENT_FEE_DETAILS ADD COLUMN INSTITUTE_SHARE_TYPE VARCHAR(10) NULL;
ALTER TABLE STUDENT_FEE_DETAILS ADD COLUMN INSTITUTE_SHARE_VALUE NUMERIC(12,2) NULL DEFAULT 0;
ALTER TABLE STUDENT_FEE_DETAILS ADD COLUMN INSTITUTE_SHARE_AMOUNT NUMERIC(12,2) NULL;
ALTER TABLE STUDENT_FEE_DETAILS ADD COLUMN TEACHER_SHARE_AMOUNT NUMERIC(12,2) NULL;
ALTER TABLE STUDENT_FEE_DETAILS ADD COLUMN OVERRIDE_INSTITUTE_SHARE NUMERIC(12,2) NULL;
ALTER TABLE STUDENT_FEE_DETAILS ADD COLUMN OVERRIDE_TEACHER_SHARE NUMERIC(12,2) NULL;
ALTER TABLE STUDENT_FEE_DETAILS ADD COLUMN OVERRIDDEN_BY UUID NULL;
ALTER TABLE STUDENT_FEE_DETAILS ADD COLUMN OVERRIDDEN_AT TIMESTAMP NULL;
