-- User service schema (user_db). JOINED inheritance: USERS base + STUDENTS/TEACHERS/PARENTS.

CREATE TABLE USERS (
    ID         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USER_TYPE  VARCHAR(31) NOT NULL,
    LOGIN_ID   VARCHAR(255) UNIQUE,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME  VARCHAR(255)
);

CREATE INDEX idx_users_login_id ON USERS (LOGIN_ID);

CREATE TABLE STUDENTS (
    ID              UUID PRIMARY KEY,
    DATE_OF_BIRTH   DATE,
    FATHER_NAME     VARCHAR(255),
    FATHER_PHONE    VARCHAR(255),
    MOTHER_NAME     VARCHAR(255),
    MOTHER_PHONE    VARCHAR(255),
    GUARDIAN_NAME   VARCHAR(255),
    GUARDIAN_PHONE  VARCHAR(255),
    EMAIL           VARCHAR(255),
    ADDRESS         TEXT,
    ENROLLMENT_DATE DATE,
    STATUS          VARCHAR(255) NOT NULL,
    CONSTRAINT fk_students_user FOREIGN KEY (ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE TABLE TEACHERS (
    ID            UUID PRIMARY KEY,
    EMPLOYEE_CODE VARCHAR(50) UNIQUE,
    EMAIL         VARCHAR(255),
    PHONE         VARCHAR(255),
    QUALIFICATION VARCHAR(255),
    JOINING_DATE  DATE,
    STATUS        VARCHAR(255) NOT NULL,
    CONSTRAINT fk_teachers_user FOREIGN KEY (ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE INDEX idx_teachers_employee_code ON TEACHERS (EMPLOYEE_CODE);

CREATE TABLE PARENTS (
    ID           UUID PRIMARY KEY,
    RELATIONSHIP VARCHAR(255),
    PHONE        VARCHAR(255),
    EMAIL        VARCHAR(255),
    ADDRESS      TEXT,
    OCCUPATION   VARCHAR(255),
    STUDENT_ID   UUID,
    STATUS       VARCHAR(255) NOT NULL,
    CONSTRAINT fk_parents_user FOREIGN KEY (ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    CONSTRAINT fk_parents_student FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (ID)
);

CREATE INDEX idx_parents_student_id ON PARENTS (STUDENT_ID);

CREATE TABLE TEACHER_AVAILABILITY (
    ID          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    TEACHER_ID  UUID NOT NULL,
    DAY_OF_WEEK VARCHAR(255),
    START_TIME  TIME,
    END_TIME    TIME,
    CONSTRAINT fk_availability_teacher FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS (ID) ON DELETE CASCADE
);

CREATE INDEX idx_availability_teacher_id ON TEACHER_AVAILABILITY (TEACHER_ID);

CREATE TABLE TEACHER_AVAILABILITY_EXCEPTIONS (
    ID                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    TEACHER_ID          UUID NOT NULL,
    EXCEPTION_DATE      DATE NOT NULL,
    REASON              VARCHAR(255),
    UNAVAILABLE_ALL_DAY BOOLEAN NOT NULL,
    START_TIME          TIME,
    END_TIME            TIME,
    CONSTRAINT fk_availability_exceptions_teacher FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS (ID) ON DELETE CASCADE
);

CREATE INDEX idx_availability_exceptions_teacher_id ON TEACHER_AVAILABILITY_EXCEPTIONS (TEACHER_ID);
