-- User service schema (user_db). JOINED inheritance: USERS base + STUDENTS / TEACHERS / PARENTS.
-- Contact fields (EMAIL, PHONE_NUMBER) live on the base USERS table. Parent<->Student is a
-- many-to-many via PARENT_STUDENTS. Uniqueness of LOGIN_ID / EMAIL / PHONE is enforced at the
-- service layer (no DB unique constraint), matching auth_db where a parent's identity is a phone.

CREATE TABLE USERS (
    ID           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USER_TYPE    VARCHAR(31) NOT NULL,
    LOGIN_ID     VARCHAR(255),
    FIRST_NAME   VARCHAR(255) NOT NULL,
    LAST_NAME    VARCHAR(255),
    EMAIL        VARCHAR(255),
    PHONE_NUMBER VARCHAR(255)
);

CREATE INDEX idx_users_login_id ON USERS (LOGIN_ID);

CREATE TABLE STUDENTS (
    ID              UUID PRIMARY KEY,
    DATE_OF_BIRTH   DATE,
    ADDRESS         TEXT,
    ENROLLMENT_DATE DATE,
    STATUS          VARCHAR(255) NOT NULL,
    CONSTRAINT fk_students_user FOREIGN KEY (ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE TABLE TEACHERS (
    ID            UUID PRIMARY KEY,
    EMPLOYEE_CODE VARCHAR(50) UNIQUE,
    QUALIFICATION VARCHAR(255),
    JOINING_DATE  DATE,
    STATUS        VARCHAR(255) NOT NULL,
    CONSTRAINT fk_teachers_user FOREIGN KEY (ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE INDEX idx_teachers_employee_code ON TEACHERS (EMPLOYEE_CODE);

CREATE TABLE PARENTS (
    ID           UUID PRIMARY KEY,
    PARENT_NAME  VARCHAR(255),
    RELATIONSHIP VARCHAR(255),
    ADDRESS      TEXT,
    OCCUPATION   VARCHAR(255),
    STATUS       VARCHAR(255) NOT NULL,
    CONSTRAINT fk_parents_user FOREIGN KEY (ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE TABLE PARENT_STUDENTS (
    PARENT_ID  UUID NOT NULL,
    STUDENT_ID UUID NOT NULL,
    PRIMARY KEY (PARENT_ID, STUDENT_ID),
    CONSTRAINT fk_parent_students_parent  FOREIGN KEY (PARENT_ID)  REFERENCES PARENTS (ID)  ON DELETE CASCADE,
    CONSTRAINT fk_parent_students_student FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (ID) ON DELETE CASCADE
);

CREATE INDEX idx_parent_students_student_id ON PARENT_STUDENTS (STUDENT_ID);

CREATE TABLE TEACHER_AVAILABILITY (
    ID          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    TEACHER_ID  UUID NOT NULL,
    DAY_OF_WEEK VARCHAR(255),
    START_TIME  TIME,
    END_TIME    TIME,
    CONSTRAINT fk_availability_teacher FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS (ID) ON DELETE CASCADE
);

CREATE INDEX idx_availability_teacher_id ON TEACHER_AVAILABILITY (TEACHER_ID);

CREATE TABLE TEACHER_AVAILABILITY_EXCEPTIONS (
    ID                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    TEACHER_ID          UUID NOT NULL,
    EXCEPTION_DATE      DATE NOT NULL,
    REASON              VARCHAR(255),
    UNAVAILABLE_ALL_DAY BOOLEAN NOT NULL,
    START_TIME          TIME,
    END_TIME            TIME,
    CONSTRAINT fk_availability_exceptions_teacher FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS (ID) ON DELETE CASCADE
);

CREATE INDEX idx_availability_exceptions_teacher_id ON TEACHER_AVAILABILITY_EXCEPTIONS (TEACHER_ID);
