-- Timetable service schema (timetable_db).

CREATE TABLE ROOMS (
    ID        UUID PRIMARY KEY,
    ROOM_NAME VARCHAR(100) NOT NULL,
    CAPACITY  INTEGER NOT NULL
);

CREATE TABLE TIMETABLES (
    ID           UUID PRIMARY KEY,
    CLASS_ID     UUID NOT NULL,
    TEACHER_ID   UUID NOT NULL,
    ROOM_ID      UUID NOT NULL,
    START_TIME   TIME NOT NULL,
    END_TIME     TIME NOT NULL,
    DAY_OF_WEEK  VARCHAR(20) NOT NULL,
    CONSTRAINT fk_timetables_room FOREIGN KEY (ROOM_ID) REFERENCES ROOMS (ID)
);

CREATE INDEX idx_timetables_teacher_id ON TIMETABLES (TEACHER_ID);
CREATE INDEX idx_timetables_class_id ON TIMETABLES (CLASS_ID);
CREATE INDEX idx_timetables_room_id ON TIMETABLES (ROOM_ID);
CREATE INDEX idx_timetables_day_of_week ON TIMETABLES (DAY_OF_WEEK);
