-- V2__update_academic_schema_uuid.sql
DROP TABLE IF EXISTS enrollments CASCADE;
DROP TABLE IF EXISTS classes CASCADE;
DROP TABLE IF EXISTS courses CASCADE;

CREATE TABLE COURSES (
    ID              UUID           PRIMARY KEY,
    COURSE_CODE     VARCHAR(50)    NOT NULL UNIQUE,
    COURSE_NAME     VARCHAR(255)   NOT NULL,
    COURSE_TYPE     VARCHAR(50),
    DESCRIPTION     TEXT,
    MONTHLY_FEE     NUMERIC(12,2)  CHECK (MONTHLY_FEE >= 0),
    ADMISSION_FEE   NUMERIC(12,2)  CHECK (ADMISSION_FEE >= 0),
    DURATION_MONTHS INT,
    STATUS          VARCHAR(50)    NOT NULL
);

CREATE TABLE CLASSES (
    ID          UUID         PRIMARY KEY,
    COURSE_ID   UUID         NOT NULL REFERENCES COURSES(ID),
    TEACHER_ID  UUID,
    CLASS_NAME  VARCHAR(255) NOT NULL,
    ROOM_NUMBER VARCHAR(50),
    CAPACITY    INT          NOT NULL CHECK (CAPACITY > 0),
    STATUS      VARCHAR(50)  NOT NULL
);

CREATE INDEX idx_classes_course_id  ON CLASSES(COURSE_ID);
CREATE INDEX idx_classes_teacher_id ON CLASSES(TEACHER_ID);

CREATE TABLE ENROLLMENTS (
    ID              UUID        PRIMARY KEY,
    STUDENT_ID      UUID        NOT NULL,
    COURSE_ID       UUID        NOT NULL REFERENCES COURSES(ID),
    CLASS_ID        UUID        NOT NULL REFERENCES CLASSES(ID),
    ENROLLMENT_DATE DATE        NOT NULL,
    STATUS          VARCHAR(20) NOT NULL,
    CONSTRAINT uq_enrollment_student_course UNIQUE (STUDENT_ID, COURSE_ID)
);

CREATE INDEX idx_enrollments_student_id ON ENROLLMENTS(STUDENT_ID);
CREATE INDEX idx_enrollments_course_id  ON ENROLLMENTS(COURSE_ID);
CREATE INDEX idx_enrollments_class_id   ON ENROLLMENTS(CLASS_ID);
