-- Exam scheduling (R19).
CREATE TABLE EXAMS (
    ID         UUID PRIMARY KEY,
    COURSE_ID  UUID NOT NULL,
    TITLE      VARCHAR(255),
    EXAM_DATE  DATE NOT NULL,
    START_TIME TIME NOT NULL,
    END_TIME   TIME NOT NULL,
    STATUS     VARCHAR(255) NOT NULL,
    CONSTRAINT fk_exams_course FOREIGN KEY (COURSE_ID) REFERENCES COURSES (ID)
);

CREATE INDEX idx_exams_course_id ON EXAMS (COURSE_ID);
