server:
  port: 8084

spring:
  application:
    name: attendance-service
  datasource:
    url: jdbc:postgresql://localhost:15432/attendance_db
    username: artacademy
    password: artacademy123
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
