server:
  port: 8087

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:15432/notification_db
    username: artacademy
    password: artacademy123
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:noreply@artacademy.com}
    password: ${MAIL_PASSWORD:changeme}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
