server:
  port: 8086

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:15432/payment_db
    username: artacademy
    password: artacademy123
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration

---
spring:
  config:
    activate:
      on-profile: docker
  flyway:
    locations: classpath:db/migration,classpath:db/seed
