server:
  port: 8088

spring:
  application:
    name: reporting-service
  datasource:
    url: jdbc:postgresql://localhost:15432/reporting_db
    username: artacademy
    password: artacademy123
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
